
export const CATALOG_REQUEST="CATALOG_REQUEST";
export const CATALOG_SUCCESS="CATALOG_SUCCESS";
export const CATALOG_FAIL="CATALOG_FAIL";


export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const PRODUCT_FAIL="PRODUCT_FAIL";